const products = [
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1125.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '2',
        name: 'Uvod u Mikroprocesorske sisteme',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1126.jpg',
        description:
            'Opis knjige Uvod u Mikroprocesorske sisteme. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa mikroprocesorskim sistemima i Еѕele da nauДЌe osnove mikroprocesorskih sistema.',
        category: 'Books',
        price: 1200.00,
        countInStock: 7,
        rating: 5.0,
        numReviews: 8,
    },
    {
        _id: '3',
        name: 'Marker',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1127.jpg',
        description:
            'Opis markera. Ovaj marker je namenjen studentima koji Еѕele da obeleЕѕe vaЕѕne delove teksta u svojim knjigama.',
        category: 'Stationery',
        price: 50.00,
        countInStock: 5,
        rating: 4.6,
        numReviews: 12,
    },
    {
        _id: '4',
        name: 'Gumica',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1129.jpg',
        description:
            'Opis gumice. Ova gumica je namenjena studentima koji Еѕele da obriЕЎu greЕЎke u svojim sveskama.',
        category: 'Stationery',
        price: 30.00,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
    },
    {
        _id: '5',
        name: 'Majica',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1130.jpg',
        description:
            'Opis majice. Ova majica je namenjena studentima koji Еѕele da pokaЕѕu svoju ljubav prema FTN Skriptarnici.',
        category: 'Merch',
        price: 1000.00,
        countInStock: 7,
        rating: 4.9,
        numReviews: 10,
    },
    {
        _id: '6',
        name: 'Ceger',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1131.jpg',
        description:
            'Opis cegera. Ovaj ceger je namenjen studentima koji Еѕele da pokaЕѕu svoju ljubav prema FTN Skriptarnici.',
        category: 'Merch',
        price: 500.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1133.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1134.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1135.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1136.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1137.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1138.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1139.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1140.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1141.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1142.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1143.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1144.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1145.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1146.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
    {
        _id: '1',
        name: 'Uvod u programiranje',
        image: 'https://matrimonia.rs/img/kolekcije/2018/all/1147.jpg',
        description:
            'Opis knjige Uvod u programiranje. Ova knjiga je namenjena studentima koji se prvi put susreД‡u sa programiranjem i Еѕele da nauДЌe osnove programiranja.',
        category: 'Books',
        price: 1200.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
    },
]

export default products